#!/usr/bin/env python3
import sys, os, subprocess, time, signal

# How to use:
# ./start_workers <FIRST_PORT> <NUM_WORKERS> <ALIVE_TIME>
# This will generate a workers.cfg file and run the workers
# for the number of seconds provided

startPort = int(sys.argv[1])
numServers = int(sys.argv[2])
aliveTime = int(sys.argv[3])

portRange = range(startPort, startPort + numServers)

with open("workers.cfg", "w") as f:
    for i in portRange:
        f.write(f"127.0.0.1:{i}")
        if i == startPort + numServers - 1:
            continue
        f.write('\n')

procs = [ 
    subprocess.Popen(["./a.out", str(i)], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE) 
    for i in portRange
]

time.sleep(aliveTime)

for p in procs:
    p.terminate()
    stdout, stderr = p.communicate(b'\n')
    print(stdout)

